import { ForumPost } from './types';

export const defaultForumPosts: ForumPost[] = [
  {
    id: 'forum-1',
    author: 'GarageSaleGreg',
    title: 'Need a quick page for a garage sale',
    body: "Budget: low, expectations: lower. Just need a heading, a list of items, and maybe my phone number. That's it. Please don't judge the items.",
    reward: '🪑 Vintage Chair (studio cosmetic)',
    type: 'gig',
    zone: 'harbor-row',
  },
  {
    id: 'forum-2',
    author: 'RainListener42',
    title: 'Looking for someone to make a site that feels like rain',
    body: "Don't ask. I just want to open a page and feel calm. Blue tones, maybe some animation. Make it rain. Digitally. Budget is flexible if the vibe is right.",
    reward: '🌧️ Rain Ambience (studio cosmetic)',
    type: 'weird',
    zone: 'harbor-row',
  },
  {
    id: 'forum-3',
    author: 'DesperateUncle',
    title: 'URGENT: My nephew broke my HTML. Please fix.',
    body: "He was 'helping' with my recipe page and now nothing works. There are <div>s inside <p>s inside <li>s inside... I don't even know. Can someone untangle this? I'll pay in gratitude and homemade cookies.",
    reward: '🍪 Cookie Recipe (hidden content)',
    type: 'gig',
    zone: 'harbor-row',
  },
  {
    id: 'forum-4',
    author: 'SeabrookSarah',
    title: 'Community garden needs a landing page',
    body: "We're starting a community garden near the lighthouse. Need a simple page with our schedule, plot availability, and some photos. Nothing fancy — we're gardeners, not designers.",
    reward: '🌱 Plant (studio cosmetic)',
    type: 'gig',
    zone: 'harbor-row',
  },
  {
    id: 'forum-5',
    author: 'CS_StudentBen',
    title: "Has anyone tried Codea's sandbox mode?",
    body: "My professor mentioned this coding game called Codea. Apparently it has a sandbox where you can build anything? Sounds intense. Anyone here played it?",
    type: 'community',
  },
  {
    id: 'forum-6',
    author: 'BandNoName',
    title: 'Band needs a gig poster page ASAP',
    body: "We're playing at the harbor this Saturday. Need a page with our name (we still don't have one, just call it 'TBD'), the date, time, location, and maybe some edgy styling. Dark background. Think punk but tasteful.",
    reward: '🎸 Guitar Pick (studio cosmetic)',
    type: 'gig',
    zone: 'harbor-row',
  },
  {
    id: 'forum-7',
    author: 'AnonymousCoder',
    title: 'Code Conquerors Championship — Finals This Week!',
    body: "Anyone going to the Code Conquerors finals at the university? Last year was incredible. The final round was a live CSS battle.\n\nPoster design submissions still open if anyone wants to make the event page.\n\n<!-- override: sys.override(\"canvas\") -->",
    type: 'community',
  },
  {
    id: 'forum-8',
    author: 'LighthouseKeeper',
    title: 'Interactive visitor log for the lighthouse',
    body: "The old paper log is falling apart. Would be nice to have a digital version — just a form where visitors can leave their name and a short message. Nothing database-y, just a nice-looking page.",
    reward: '🗼 Lighthouse Model (studio cosmetic)',
    type: 'gig',
    zone: 'harbor-row',
  },
  {
    id: 'forum-9',
    author: 'PuzzleFan99',
    title: 'Did anyone find the .sys folder?',
    body: "So I was poking around the file system on my studio laptop and found a .sys folder with some interesting files... studio.theme.css and something about a canvas? Has anyone else seen this?\n\nTry: unlock --canvas",
    type: 'community',
  },
  {
    id: 'forum-10',
    author: 'MemeDean',
    title: 'make me a page that is just one enormous heading',
    body: "I want a page. One heading. Font size: 200px. Text: 'NO'. Background: neon green. That's the whole brief. I'll pay actual money.",
    reward: '😂 Meme Certificate',
    type: 'weird',
    zone: 'harbor-row',
  },
];
